.TH "YUBISERVER" "1" 
.SH "NAME" 
yubiserver \(em Simple and lightweight Yubikey OTP and HOTP/OATH validation server. 
.SH "SYNOPSIS" 
.PP 
\fByubiserver [options] \fR 
.SH "DESCRIPTION" 
.PP 
\fByubiserver\fR is a free simple and lightweight Yubikey 
OTP (One Time Password) and HOTP/OATH validation server. 
.SH "OPTIONS" 
.PP 
These programs follow the usual GNU command line syntax, 
with long options starting with two dashes (`\-').  A summary of 
options is included below.   
 
.IP "\fB-l\fP           \fB\-\-logfile\fP         " 10 
Use this as logfile. 
.IP "\fB-d\fP           \fB\-\-database\fP         " 10 
Use this SQLite3 database file. 
.IP "\fB-p\fP           \fB\-\-port\fP         " 10 
Port to bind the server. Default port is 8000. 
.IP "\fB-h\fP           \fB\-\-help\fP         " 10 
Show summary of options. 
.IP "\fB-V\fP           \fB\-\-version\fP         " 10 
Show version of program. 
.SH "SEE ALSO" 
.PP 
yubiserver-admin (1). 
.SH "AUTHOR" 
.PP 
This manual page was written by Nanakos Chrysostomos <nanakos@wired-net.gr> for 
the \fBDebian GNU/Linux\fP system (and may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any 
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Sat 29 Oct 2011, 19:16 
